version: "3.9"

services:
  app:
    build: .
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: development
    depends_on:
      - db-postgres-medicao

  db-postgres-medicao:
    image: postgres:latest
    container_name: "db-postgres-medicao"
    ports:
      - "5435:5432"
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
